const assert = require('node:assert/strict');
const { chromium } = require('playwright-core');
const fs = require('node:fs/promises');
const path = require('node:path');
const origin = 'http://127.0.0.1:4173';
const note = 'After lunch, Margaret sat by the window and told Anna about the roses she used to grow.';
const sleep = 'Woke twice overnight and settled after reassurance.';
(async () => {
  const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 390, height: 932 }, deviceScaleFactor: 3, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const destination = path.resolve(__dirname, '..', 'client-screenshots');
  const assets = path.resolve(__dirname, '..', 'dist', 'assets', 'presentation');
  await fs.mkdir(destination, { recursive: true });
  async function shot(name, full = true) {
    await page.evaluate(() => document.fonts.ready);
    if (await page.locator('.toast.visible').count()) await page.waitForFunction(() => !document.querySelector('.toast').classList.contains('visible'));
    if (full) await page.setViewportSize({ width: 390, height: await page.evaluate(() => Math.max(932, Math.ceil(document.documentElement.scrollHeight))) });
    await page.screenshot({ path: path.join(destination, name + '.png'), animations: 'disabled' });
    await fs.copyFile(path.join(destination, name + '.png'), path.join(assets, name + '.png'));
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, name + ' horizontal overflow');
    await page.setViewportSize({ width: 390, height: 932 });
  }
  const answer = (key, value) => page.locator(`[data-item="${key}"][data-answer="${value}"]`).click();
  try {
    await page.goto(origin + '/care.html?embed=1');
    assert.equal(await page.locator('[aria-pressed="true"]').count(), 0);
    assert.deepEqual(await page.locator('[data-mood]').allTextContents(), ['Calm', 'Cheerful', 'Withdrawn', 'Anxious', 'Agitated']);
    assert.equal(await page.locator('.mood-face svg').count(), 5);
    await answer('breakfast', 'well');
    assert.match(await page.locator('#item-breakfast').innerText(), /Recorded by Anna/);
    assert.equal(await page.locator('#item-breakfast [data-answer="well"]').isVisible(), true);
    assert.equal(await page.locator('#item-breakfast [data-answer="well"]').getAttribute('aria-pressed'), 'true');
    for (const meal of ['lunch','dinner']) assert.match(await page.locator('#item-' + meal).innerText(), /Later today/);
    for (const meal of ['lunch','dinner']) assert.equal(await page.locator(`#item-${meal} [data-answer="well"]`).isVisible(), true);
    assert.equal(await page.locator('[data-reopen], [data-collapse]').count(), 0);
    assert.equal(await page.locator('[data-mood="Calm"]').isVisible(), true);
    await shot('01-morning');
    await page.locator('.mobile-menu > summary').click();
    assert.match(await page.locator('#menu-caregiver').innerText(), /CAREGIVER\s+Anna Lewis/);
    await shot('06-caregiver-menu', false);
    await page.locator('.mobile-menu > summary').click();
    await answer('lunch', 'well');
    await answer('am', 'given');
    for (const key of ['shower','grooming']) await answer(key, 'Done');
    await page.locator('[data-mood="Calm"]').click();
    await page.locator('[data-sleep="Restless"]').click();
    await page.locator('#detail-note').fill(sleep);
    await page.locator('#detail-form > .primary-button').click();
    await page.locator('[data-concern="none"]').click();
    await page.locator('[data-detail="note"]').click();
    await page.locator('#detail-note').fill(note);
    await page.locator('#detail-form > .primary-button').click();
    assert.equal(await page.locator('#care-count').textContent(), '8 of 10 recorded');
    await page.evaluate(() => scrollTo(0, 0));
    await shot('02-anna-end');
    await page.locator('#save-part').click();
    assert.match(await page.locator('#shift-dialog').innerText(), /Nothing has been sent to the family/);
    await shot('07-saved-part', false);
    await Promise.all([page.waitForNavigation({waitUntil:'load'}), page.locator('[data-caregiver="jane"]').click()]);
    assert.match(await page.locator('#active-caregiver').innerText(), /Jane/);
    for (const [key, val] of [['dinner','well'],['pm','given']]) assert.equal(await page.locator(`[data-item="${key}"][data-answer="${val}"]`).isVisible(), true);
    assert.match(await page.locator('#item-lunch').innerText(), /Recorded by Anna/);
    assert.equal(await page.locator('[data-item="lunch"][data-answer="well"]').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('[data-mood="Calm"]').isVisible(), true);
    assert.equal(await page.locator('[data-mood="Calm"]').getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('#item-mood').innerText(), /Recorded by Anna/);
    assert.equal(await page.locator('[data-reopen], [data-collapse]').count(), 0);
    assert.equal(await page.evaluate(() => DailyCare.state.by.mood), 'anna');
    await page.evaluate(() => scrollTo(0, 0));
    await shot('03-handover');
    await answer('dinner', 'well');
    await page.locator('#review-link').click();
    await page.waitForURL(/review\.html/);
    assert.match(await page.locator('#summary-meals').innerText(), /Dinner\s+Recorded by Jane\s+Ate well/);
    assert.match(await page.locator('#summary-medication').innerText(), /PM medication\s+Not recorded/);
    assert.ok((await page.locator('#review-changes').innerText()).includes(sleep));
    assert.equal(await page.locator('#review-note').innerText(), note);
    assert.equal(await page.locator('#send-update').isDisabled(), true);
    await shot('08-missing-review');
    await page.locator('#send-unrecorded').check();
    await page.locator('#send-update').click();
    await page.locator('#view-family').click();
    await page.waitForURL(/family\.html/);
    assert.match(await page.locator('#family-gaps').innerText(), /PM medication was not recorded/);
    assert.doesNotMatch(await page.locator('#family-day').innerText(), /evening medication was given|morning and evening medication were given/);
    assert.equal(await page.locator('#review-note').innerText(), note);
    assert.equal(await page.locator('#family-signature').textContent(), 'Anna Lewis and Jane Doe');
    await shot('09-family-with-gap');
    // Preserve the real recorded day while verifying the return-to-item path.
    const gapState = await page.evaluate(() => DailyCare.state);
    await page.goto(origin + '/review.html?embed=1#' + encodeURIComponent(JSON.stringify(gapState)));
    await page.locator('#missing-list a').click();
    await page.waitForURL(/care\.html/);
    await answer('pm', 'given');
    await page.locator('#save-part').click();
    await page.locator('#shift-dialog a').click();
    await page.waitForURL(/review\.html/);
    assert.equal(await page.locator('#missing-items').isHidden(), true);
    assert.match(await page.locator('#summary-medication').innerText(), /PM medication\s+Recorded by Jane\s+Given/);
    await shot('04-final-review');
    await page.locator('#send-update').click();
    await page.locator('#view-family').click();
    await page.waitForURL(/family\.html/);
    assert.equal(await page.locator('#family-gaps').isHidden(), true);
    assert.match(await page.locator('#family-day').innerText(), /Margaret ate well at breakfast, lunch and dinner/);
    await shot('05-family-update');
    await page.goto(origin + '/care.html?embed=1&stage=anna-end&detail=sleep');
    await shot('10-sleep-detail', false);
    for (const width of [320, 430, 900]) {
      await page.setViewportSize({ width, height: 932 });
      await page.goto(origin + '/care.html?embed=1&stage=morning');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'overflow at ' + width);
    }
    assert.deepEqual(errors, []);
    console.log('Verified Anna-to-Jane handover, missing-item completion, both family updates, original mood faces and mobile layouts. Screenshots exported.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
